### PR TITLE
Dockerfile for Sumokoin

### PR DESCRIPTION
**Pull request by billaue2**
For docker build

### CODE REVIEW

**Comment by stoffu** [comment]
Code stolen from Monero without credit: #70

**Comment by heptathlon** [comment]
Legally there's nothing that can be done about this I think. The same happened to me on another project at Nextcloud where ownCloud (which Nextcloud is forked from) copied a patch without giving credit. The problem was that the guy who submitted the patch was not working for ownCloud, so legally it wasn't their fault. For sure the guy was working for ownCloud and just using a throwaway account to submit the patch & remove copyright notices.

**Comment by stoffu** [comment]
Thanks for sharing your experience. FWIW @billaue2 is among the four Sumokoin Core developers:

> Core developers:
> 
> - Sumoshi Tanaka
> 
> - Haruto Tanno
> 
> - Bill Aue
> 
> - Vu Quang

https://bitcointalk.org/index.php?topic=1905086 

But they're all anonymous, so I wonder if it's possible to take any legal actions when required.

**Comment by oddsigve** [comment]
Haruto Tanno and Vu Hong Quang is not anonymous. This you know, so why indicate otherwise?

**Comment by stoffu** [comment]
@oddsigve 
Why do you assume these names are real? Most likely they're pseudonyms. Otherwise please point me to anywhere that proves their identities. I can easily understand that it's a huge risk to reveal their real identities especially for such a shady project with absurd premine.

**Comment by sunk818** [comment]
This is not telegram or bitcoin talk. Please keep this professional and on topic. If you have an issue with attribution, let's address that. Your opinion about the sumokoin project is not relevant.

**Comment by stoffu** [comment]
@sunk818 
Sorry for going slightly off topic. What matters here is whether the Sumokoin developers are willing or not to credit Monero's original patches when they merge them to their repository.

**Pull request merged**
