### PR TITLE
[P2P] Add P2P_DEFAULT_CONNECTIONS_COUNT hardcoded limit to incoming peers as well

### PR DESCRIPTION
**Pull request by sumogr**
The default connections count from config.h was applied only to outgoing connections (connections created by us) and not on the incoming connections (connections created by remote others to our node) so the incoming connections could be of any number unless a max limit was set. I think it was omitted by mistake. For that reason I am also increasing the default connections count by 4.

### CODE REVIEW

**Comment by quangvu3** [comment]
I don't think incoming connections were left with no limit is a mistake. Node is supposed to serve a many as possible peers. Some questions:

1. Why limit is better?
2. Why to increase outgoing connections from 8 to 12? I think we can always create a seperated P2P_DEFAULT_INCOMING_CONNECTIONS_COUNT instead using 12 for both

**Comment by sumogr** [comment]
If node is supposed to serve as many as possible peers then there is no reason to add an out connections default number too.  Nodes cannot handle an unlimited amount of connections. The only difference between out and in peers is that outs are initiated by us (from the peerlists) while ins from the remote nodes towards us in the same way. What's the point of setting a limit in outs and not in incomings. Other projects have fixed this as well SWAP for example https://github.com/swap-dev/swap/commit/997ab000c0c1a3f9586d7fc9d4e96ee87f0c9949 or by setting a separate default count for outs and ins but still setting one like LOKI https://github.com/loki-project/loki/commit/5543cb9bd73a8d6b097e85ef14c52deb21917ba8 . I increased the number of default counts to make sure that we always have a big enough sample of connections for fast syncing cause up to now we had maximum 12 outs and an unlimited number of incomings

**Comment by quangvu3** [comment]
Thanks for explanation, I prefer Loki's way, so 12 for out, and 32 for in should be fine. Can you push a commit for that?

**Comment by sumogr** [comment]
sure :) closing this and making a new one

**Pull request closed without merging**
