### PR TITLE
[DAEMON] Output a new block msg on each new block

### PR DESCRIPTION
**Pull request by Aris-sumogr**
Output a new block msg on each new block + count of remotes in normal_state so we know daemon is running and is ok. Same line printing

### CODE REVIEW

**Comment by quangvu3** [comment]
Why does the msg be handled only at `handle_notify_new_fluffy_block`? 

Ofc we can see full block added info at log level 1 but often mixing with other debug info so I prefer bringing full block info to level 0 somehow

**Comment by sumogr** [comment]
ok I agree. Leave the pull as is, i will bring the message for notify new full block from 1 to 0 on the same pull and revert the commit

**Comment by Aris-sumogr** [comment]
Quite a mess to bring the new block added info to level 0 cause it is performed on blockchain.cpp for each block that gets added on stored at db chain, the daemon being synced or not. That will spam the display while syncing or i ll have to import headers there from cryptonote protocol and make an if statement for bring it to 0 when synced leaving it to 1 while syncing. Let it be. I ll try another approach, I 'll pop up a message every 10 minutes declaring height and synced state and if all is ok (a simpler status call showing that evertyhing is fine)

**Comment by Aris-sumogr** [comment]
Closing this for the time being till i think of a good way to implement it, time loops are thread bombs when applied no matter what

**Pull request closed without merging**
