### PR TITLE
[depends] Amend fallback address to point to sumokoin server 

### PR DESCRIPTION
**Pull request by sumogr**
Enough with chasing broken links, servers being down, obsolete repos, amended file names and so on...
Move all deps on sumokoin.org server and download from there. Make changes only if a version update at any of the dependencies is needed.

MacOSX10.11.sdk for macOS binaries can be downloaded from https://www.sumokoin.org/depends/MacOSX10.11.sdk.tar.xz

### CODE REVIEW

**Comment by quangvu3** [comment]
Though it looks convenient, it'll create single point of failure and take time to maintain IMO

**Comment by sumogr** [comment]
> Though it looks convenient, it'll create single point of failure and take time to maintain IMO

@quangvu3  true, i was angry with chasing broken links when i did this. What I ll'do is amend this and just restore the **fallback address** to point to sumokoin's server instead of each dependency separately

**Comment by sumogr** [comment]
Done

**Comment by sumogr** [comment]
closing and recreating cause fixing conflicts dissociate

**Pull request closed without merging**
