### PR TITLE
fix: Fix error OPENSSL when build on Ubuntu

### PR DESCRIPTION
**Pull request by littleSand**

### CODE REVIEW

**Comment by quangvu3** [comment]
This worked for me, thank you

**Comment by haruto-tanno** [comment]
Worked for me on Ubuntu 16.04 too. However, I'd prefer putting `${EXTRA_LIBRARIES}` at the end of the lib inclusion lines for better code convention

**Comment by littleSand** [comment]
Hi @haruto-tanno , i did as you said.

**Comment by haruto-tanno** [comment]
Thanks @littleSand ;)

**Pull request merged**
